GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/5ce0dae8492aeebfb59afb65

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Web Dev Simplified"
}

###

DELETE http://localhost:3000/subscribers/5ce0dae8492aeebfb59afb65

###

PATCH http://localhost:3000/subscribers/5ce0dae8492aeebfb59afb65
Content-Type: application/json

{
    "name": "New Name"
}